inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile*'
  Exclude:
    - lib/generators/*/templates/**/*
    - '**/Gemfile*.lock'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  Exclude:
    - test/**/*

Lint/UnusedMethodArgument:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
