addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
bundler_args: --clean --jobs=3 --retry=3
cache: bundler
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - Gemfile
  - gemfiles/Gemfile.rails-4.2.x
language: ruby
matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: 2.2
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: ruby-head
  include:
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: jruby-19mode
      jdk: openjdk7
    - gemfile: gemfiles/Gemfile.rails-4.0.x
      rvm: jruby-19mode
      jdk: openjdk7
    - gemfile: Gemfile
      rvm: jruby-19mode
      jdk: openjdk7
    - gemfile: gemfiles/Gemfile.rails-4.2.x
      rvm: jruby-19mode
      jdk: openjdk7
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
sudo: false
